version: "3.8"
services:
  task-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - POSTGRES_USER=task_manager
      - POSTGRES_PASSWORD=SecureP@ssw0rd!
      - POSTGRES_DB=task_management
      - DB_DRIVER=postgres
      - DB_SOURCE=host=postgres user=task_manager password=SecureP@ssw0rd! dbname=task_management port=5432 sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: task_manager
      POSTGRES_PASSWORD: SecureP@ssw0rd!
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_manager"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: